blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/apollo
    about: For quick questions or real-time discussion. Note that issues are searchable and help others with the same question.
